### ISSUE TITLE
Improve packaging (mamba?)

### ISSUE THREAD

**Issue by telegraphic** [UCBerkeleySETI/hyperseti#104]
Try and make easier to install. As hyperseti depends on cupy, could look at using conda-style requirements. I've previously updated pyproject.toml for poetry, but now feel it's not a good fit

**Comment by telegraphic** [comment]
Playing around with `mambaforge`, it is much quicker than conda and a no-brainer to switch over IMO. (I don't think this will affect packaging approach though?)

**Comment by telegraphic** [comment]
```yaml
# conda env create -f environment.yml
name: hyper
channels:
  - conda-forge
dependencies:
  - cupy
  - cutensor
  - jupyterlab
  - ipywidgets
  - h5py
  - hdf5plugin
  - numpy
  - scipy
  - pandas
  - matplotlib
  - logbook
  - astropy
  - pyyaml
  - pytest
  - pytest-cov
  - pytest-runner
  - pytest-order
  - codecov 
```
