### ISSUE TITLE
Provide example findET config yaml file

### ISSUE THREAD

**Issue by marcowenwolf** [UCBerkeleySETI/hyperseti#114]
The config construct is available as python dict, but it takes some rework to covert this into a sample YAML config. Can you add an example yaml file to this repo, having e.g. below content:

```
---
preprocess:
  sk_flag: true
  normalize: true
  blank_edges:
    n_chan: 32
  blank_extrema:
    threshold: 10000
dedoppler:
  kernel: ddsk
  max_dd: 10
  apply_smearing_corr: true
  plan: stepped
hitsearch:
  threshold: 20
pipeline:
  merge_boxcar_trials: true
```
